name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 22 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
        python scraper.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
